### ISSUE TITLE
protonet_miniimagenet example not working

### ISSUE THREAD

**Issue by arshamkhodajoo** [learnables/learn2learn#341] opened 2022-08-11 05:30 UTC
Hi, I tried to run this code on Google Colab:
```python
train_dataset = l2l.vision.datasets.MiniImagenet(
        root="mini-test", mode='train', download=True)
valid_dataset = l2l.vision.datasets.MiniImagenet(
        root="mini-test", mode='validation', download=True)
test_dataset = l2l.vision.datasets.MiniImagenet(
        root="mini-test", mode='test', download=True)
```

and this is what I get:
```
---------------------------------------------------------------------------
UnpicklingError                           Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/learn2learn/vision/datasets/mini_imagenet.py](https://localhost:8080/#) in __init__(self, root, mode, transform, target_transform, download)
    104             with open(pickle_file, 'rb') as f:
--> 105                 self.data = pickle.load(f)
    106         except pickle.UnpicklingError:

UnpicklingError: invalid load key, '<'.

During handling of the above exception, another exception occurred:

UnpicklingError                           Traceback (most recent call last)
1 frames
[<ipython-input-14-d0cb68a5fa4e>](https://localhost:8080/#) in <module>()
      1 train_dataset = l2l.vision.datasets.MiniImagenet(
----> 2         root="mini-test", mode='train', download=True)
      3 valid_dataset = l2l.vision.datasets.MiniImagenet(
      4         root="mini-test", mode='validation', download=True)
      5 test_dataset = l2l.vision.datasets.MiniImagenet(

[/usr/local/lib/python3.7/dist-packages/learn2learn/vision/datasets/mini_imagenet.py](https://localhost:8080/#) in __init__(self, root, mode, transform, target_transform, download)
    109                 download_file(dropbox_file_link, pickle_file)
    110             with open(pickle_file, 'rb') as f:
--> 111                 self.data = pickle.load(f)
    112 
    113         self.x = torch.from_numpy(self.data["image_data"]).permute(0, 3, 1, 2).float()

UnpicklingError: invalid load key, '<'.
```

**Comment by seba-1511** [comment] 2022-08-11 05:35
The issue is the same as in #310, so I'm closing this.

**Closed by seba-1511** 2022-08-11 05:35 UTC
