### ISSUE TITLE
Not importing vision by default

### ISSUE THREAD

**Issue by vkkhare** [learnables/learn2learn#149] opened 2020-06-12 12:01 UTC
I would like to know if we can remove `from . import vision` in the` __init__.py` for the learn2learn module. I would just like to use the algorithms and not the datasets since I have my own. I tried building from scratch after removing the dependency from init and by removing all the extensions from [setup.py](https://github.com/learnables/learn2learn/blob/master/setup.py#L35)   but still got errors

Decoupling this would also help in decoupling torchvision dependency. 
Running the module as it is I get an error 
```
TypeError: _resolve_type_from_object(): incompatible function arguments. The following argument types are supported:
    1. (arg0: object, arg1: torch._C._jit_tree_views.SourceRange, arg2: Callable[[str], function]) -> torch._C.Type

Invoked with: typing.Union[int, NoneType], None, <function try_ann_to_type.<locals>.fake_rcb at 0x7f835df637b8>
```

A simple search described this issue comes when we don't have support for JIT.

my setup is as follows:

- learn2learn==0.1.1

- torch==1.5.0+cu101

- torchtext==0.6.0

- torchvision==0.6.0+cu101

**Comment by seba-1511** [comment] 2020-06-13 17:35
Hello @vkkhare ,

Removing that import is possible, but tedious. Could you provide more details for what you would need it removed? (e.g. why vision and not gym or text? Is it to get rid of torchvision?)

Regarding the error message, do you have a colab/script to reproduce it?

**Comment by vkkhare** [comment] 2020-06-14 00:55
Yeah I got the above error when it tried to import vision and hence I tried to remove vision. But the argument follows for gym and text also.

The error comes when importing datasets. I ran this on my personal pc. Will put up a colab report soon

**Comment by seba-1511** [comment] 2020-06-14 17:03
OK, thanks for the bug report. Some questions to attempt to fix this:

* Did you install learn2learn from sources or via pip?
* If from sources, do you have Cython installed? If from pip, what's the version of your C compiler?
* Do you also get an error if you import those datasets directly from torchvision (i.e. not through learn2learn)?

**Comment by vkkhare** [comment] 2020-06-19 12:39
Hi @seba-1511 Sorry for delayed response! 

- I installed learn2learn via pip. My C compiler is gcc (Ubuntu 5.5.0-12ubuntu1~16.04) 5.5.0 20171010

- Hmm I get this error even via directly running torchvision. I guess this is an issue with pytorch 1.5.0+ then. I will ping pytorch forum for this. Thanks!

**Comment by seba-1511** [comment] 2020-06-19 15:07
Thanks for your answers. I'll close this thread, as the issue seems to be with one of the dependencies (torch/torchvision). Please re-open if it isn't, and we can have a closer look.

**Closed by seba-1511** 2020-06-19 15:07 UTC
