### ISSUE TITLE
Add MNIST or Omniglot to README

### ISSUE THREAD

**Issue by ian-bunner** [learnables/learn2learn#61] opened 2019-09-20 06:02 UTC
The current demonstration of how to use l2l in the README is for a RL example. This creates the false impression that l2l is a RL library. We should also include a supervised/deep-learning example (possibly side by side?) to make l2l more welcoming for those w/o an RL focus.

**Comment by seba-1511** [comment] 2020-02-22 19:49
Duplicate of #67

**Closed by seba-1511** 2020-02-22 19:49 UTC
